const fs = require('fs');
let js = fs.readFileSync('public/assets/js/midicontrols.v4.js', 'utf8');
let html = fs.readFileSync('index.html', 'utf8');

// Add "Import from .syx" button to HTML (Manager panel)
const dmImportTarget = `<input type="file" id="import-device-input" accept=".json" style="display:none" onchange="handleImportDevice(event)">`;
const dmImportReplacement = `<input type="file" id="import-device-input" accept=".json,.syx" style="display:none" onchange="handleImportDevice(event)">`;
html = html.replace(dmImportTarget, dmImportReplacement);

// Update handleImportDevice to handle .syx files
const handleImportTarget = `function handleImportDevice(evt) {
  const file = evt.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = e => {
    try {
      const data = JSON.parse(e.target.result);
      if (!data.id || !data.controls) throw new Error("Invalid structure");
      
      previewDraft = data;`;

const handleImportReplacement = `function handleImportDevice(evt) {
  const file = evt.target.files[0];
  if (!file) return;
  const isSyx = file.name.toLowerCase().endsWith('.syx');
  const reader = new FileReader();
  reader.onload = e => {
    try {
      let data;
      if (isSyx) {
        const bytes = new Uint8Array(e.target.result);
        if (bytes[0] === 0xF0 && bytes[1] === 0x7D && bytes[bytes.length - 1] === 0xF7) {
          const jsonBytes = bytes.slice(2, bytes.length - 1);
          const jsonStr = new TextDecoder().decode(jsonBytes);
          data = JSON.parse(jsonStr);
        } else {
          throw new Error("Invalid .syx format (Not generated by MIDIcontrolz2)");
        }
      } else {
        data = JSON.parse(e.target.result);
      }
      
      if (!data.id || !data.controls) throw new Error("Invalid structure");
      
      previewDraft = data;`;
js = js.replace(handleImportTarget, handleImportReplacement);

const readAsTextTarget = `    } catch(err) {
      toast("Invalid JSON file.", "error");
    }
    evt.target.value = "";
  };
  reader.readAsText(file);
}`;

const readAsTextReplacement = `    } catch(err) {
      toast("Invalid file: " + err.message, "error");
    }
    evt.target.value = "";
  };
  if (isSyx) {
    reader.readAsArrayBuffer(file);
  } else {
    reader.readAsText(file);
  }
}`;
js = js.replace(readAsTextTarget, readAsTextReplacement);

// Add Import .syx to the Editor buttons
const exportJsonTarget = `<button class="btn" onclick="exportPresetJSON()">📤 Export JSON</button>
        <button class="btn" onclick="exportDeviceSyx('\${dev.id}')">📤 Export .syx</button>`;
const exportJsonReplacement = `<button class="btn" onclick="document.getElementById('import-device-input').click()">📥 Import</button>
        <button class="btn" onclick="exportPresetJSON()">📤 Export JSON</button>
        <button class="btn" onclick="exportDeviceSyx('\${dev.id}')">📤 Export .syx</button>`;
js = js.replace(exportJsonTarget, exportJsonReplacement);

fs.writeFileSync('index.html', html);
fs.writeFileSync('public/assets/js/midicontrols.v4.js', js);
console.log('Import Syx fixed!');
