const fs = require('fs');
let js = fs.readFileSync('public/assets/js/midicontrols.v4.js', 'utf8');

const target = `function handleImportDevice(evt) {
  const file = evt.target.files[0]; if (!file) return;
  const reader = new FileReader();
  reader.onload = e => {
    try {
      const dev = JSON.parse(e.target.result);
      if (!dev.id || !dev.name) throw new Error('Missing id or name');
      const idx = State.devices.findIndex(d => d.id === dev.id);
      if (idx >= 0) State.devices[idx] = dev; else State.devices.push(dev);
      save(); populateDeviceDropdown(); renderDeviceManager();
      toast(\`Device "\${dev.name}" imported ✓\`, 'success');
    } catch(e) { toast('Invalid device JSON: ' + e.message, 'error'); }
  };
  reader.readAsText(file);
  evt.target.value = '';
}`;

const replacement = `let previewDraft = null;
function handleImportDevice(evt) {
  const file = evt.target.files[0]; if (!file) return;
  const isSyx = file.name.toLowerCase().endsWith('.syx');
  const reader = new FileReader();
  
  reader.onload = e => {
    try {
      let data;
      if (isSyx) {
        const bytes = new Uint8Array(e.target.result);
        if (bytes[0] === 0xF0 && bytes[1] === 0x7D && bytes[bytes.length - 1] === 0xF7) {
          const jsonBytes = bytes.slice(2, bytes.length - 1);
          const jsonStr = new TextDecoder().decode(jsonBytes);
          data = JSON.parse(jsonStr);
        } else {
          throw new Error("Invalid .syx format (Not generated by MIDIcontrolz2)");
        }
      } else {
        data = JSON.parse(e.target.result);
      }
      
      if (!data.id || !data.name) throw new Error('Missing id or name');
      
      previewDraft = data;
      
      const preset = data.defaultPresets?.[0] || {};
      const tags = data.tags && data.tags.length > 0 ? data.tags.join(', ') : 'None';
      
      let knobsHtml = (preset.knobs || data.controls?.knobs || []).map(k => \`<div style="display:flex;justify-content:space-between;border-bottom:1px solid var(--surface3);padding:2px 0;"><span>\${k.label || 'Knob'}</span><span>CC \${k.cc}</span></div>\`).join('');
      let padsHtml = (preset.pads || data.controls?.pads || []).map(p => \`<div style="display:flex;justify-content:space-between;border-bottom:1px solid var(--surface3);padding:2px 0;"><span>\${p.label || 'Pad'}</span><span>Note \${p.note}</span></div>\`).join('');
      
      const html = \`
        <h3 style="margin-top:0;font-size:1.2rem;border-bottom:1px solid var(--border);padding-bottom:8px;">Preview Import: \${data.name}</h3>
        <p style="font-size:0.85rem;color:var(--text2);margin-bottom:12px;">\${data.description||'No description provided.'}</p>
        <div style="font-size:0.85rem;margin-bottom:12px;background:var(--surface2);padding:6px;border-radius:4px;"><strong>Tags:</strong> \${tags}</div>
        <div style="display:flex;gap:16px;flex-wrap:wrap;">
          <div style="flex:1;min-width:200px;">
            <h4 style="border-bottom:1px solid var(--border);padding-bottom:4px;margin-bottom:8px;font-size:1rem;">Mapped Knobs</h4>
            <div style="font-size:0.8rem;height:140px;overflow-y:auto;background:var(--surface2);padding:8px;border-radius:6px;border:1px solid var(--border);">
              \${knobsHtml || '<span style="color:var(--text3);">No knobs mapped</span>'}
            </div>
          </div>
          <div style="flex:1;min-width:200px;">
            <h4 style="border-bottom:1px solid var(--border);padding-bottom:4px;margin-bottom:8px;font-size:1rem;">Mapped Pads</h4>
            <div style="font-size:0.8rem;height:140px;overflow-y:auto;background:var(--surface2);padding:8px;border-radius:6px;border:1px solid var(--border);">
              \${padsHtml || '<span style="color:var(--text3);">No pads mapped</span>'}
            </div>
          </div>
        </div>
        <div style="margin-top:20px;display:flex;gap:12px;justify-content:flex-end;">
          <button class="btn" onclick="closeModal()">Cancel</button>
          <button class="btn primary" onclick="confirmImportDevice()">Import Preset</button>
        </div>
      \`;
      openModal(html);
      
    } catch(err) { toast('Invalid file: ' + err.message, 'error'); }
  };
  
  if (isSyx) {
    reader.readAsArrayBuffer(file);
  } else {
    reader.readAsText(file);
  }
  evt.target.value = '';
}

function confirmImportDevice() {
  if (!previewDraft) return;
  const dev = previewDraft;
  const idx = State.devices.findIndex(d => d.id === dev.id);
  if (idx >= 0) State.devices[idx] = dev; else State.devices.push(dev);
  save(); populateDeviceDropdown(); renderDeviceManager();
  toast(\`Device "\${dev.name}" imported ✓\`, 'success');
  closeModal();
  previewDraft = null;
}`;

if (js.includes(target)) {
  js = js.replace(target, replacement);
  fs.writeFileSync('public/assets/js/midicontrols.v4.js', js);
  console.log("Import patched!");
} else {
  console.log("Target not found!");
}
